base-image: ghcr.io/ublue-os/bazzite:latest

rpm:
  - steam
  - gamemode
  - mangohud
  - lutris
  - neofetch
  - htop
  - gnome-tweaks
  - power-profiles-daemon

flatpak:
  - com.obsproject.Studio
  - org.kde.krita
  - com.discordapp.Discord
  - org.gimp.GIMP

system:
  hostname: robe231-bazzite
  timezone: Europe/Vilnius
  auto-update: true
  telemetry: false
